# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenCharge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenCharge
pod 'Alamofire'

  target 'OpenChargeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenChargeUITests' do
    # Pods for testing
  end

end
